version: '3.4'

services:
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
   
  discount.api:
    image: ${DOCKER_REGISTRY-}discount
    build:
      context: .
      dockerfile: Services/Discount/Discount.Api/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

      
  catalogdb:
    image: mongo
         
  portainer:
    image: portainer/portainer-ce
     
  basketdb:
    image: redis:alpine   
    
  discountdb:
    image: postgres
    
  pgadmin:
    image: dpage/pgadmin4

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest



volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

