version: '3.4'

services:
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "MongoSettings__ConnectionString=mongodb://catalogdb:27017"
      - "MongoSettings__Db=CatalogDb"
      - "MongoSettings__CollectionName=Products"      
    ports:
      - "8000:80"
      #- "8800:443"
      
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro 
    depends_on:
      - catalogdb

  catalogdb: 
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db